name: SurvivelistWarnings
version: ${project.version}
main: itzshmulik.survivelist.survivelistwarnings.SurvivelistWarnings
api-version: 1.17
authors: [ ItzShmulik, The_Regurgitator ]
description: Survivelist's advanced warning system!
commands:
  warn:
    description: Allows a staff member to warn a player.
  wreload:
    description: Reloads plugin's config.
